version: '3.7'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - frontend
      - api
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - './frontend/project:/usr/src/app'
      - '/user/src/app/node_modules'
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - api
      - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    env_file:
      - ./api/.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env.dev

volumes:
  postgres_data: